
import React from 'react';
import { Sparkles, ArrowRight, Gamepad2, BrainCircuit, Mic } from 'lucide-react';

interface WelcomeScreenProps {
  onStart: () => void;
}

const WelcomeScreen: React.FC<WelcomeScreenProps> = ({ onStart }) => {
  const handleStart = async () => {
    if (window.aistudio) {
      const hasKey = await window.aistudio.hasSelectedApiKey();
      if (!hasKey) {
        await window.aistudio.openSelectKey();
        // Proceeding immediately as per guidelines to avoid race conditions
      }
    }
    onStart();
  };

  return (
    <div className="flex flex-col items-center justify-center min-h-[75vh] px-4 animate-fadeIn relative pt-20 md:pt-32">
      <div className="text-center max-w-3xl mx-auto mb-12">
        <div className="inline-flex items-center gap-2 px-4 py-1.5 bg-white/60 backdrop-blur-sm text-emerald-700 text-xs font-bold rounded-full mb-3 border border-white shadow-sm animate-bounce-slow">
            <Sparkles className="w-3 h-3 text-emerald-500" /> 
            <span>Gemini 3 Pro + 2.5 Flash</span>
        </div>
        
        <h1 className="text-5xl md:text-7xl font-extrabold text-slate-900 mb-6 tracking-tight leading-[1.1]">
          Design Your Future <br/>
          <span className="text-transparent bg-clip-text bg-gradient-to-r from-emerald-600 to-teal-500">With Intelligence</span>
        </h1>
        
        <p className="text-lg md:text-xl text-slate-600 leading-relaxed max-w-2xl mx-auto mb-8">
          CareerSage is your personal AI career strategist. 
          Powered by latest Gemini models to help you navigate 
          education, jobs, and dreams.
        </p>

        <div className="flex flex-col items-center gap-4">
            <button 
                onClick={handleStart}
                className="group relative inline-flex items-center gap-3 px-8 py-4 bg-slate-900 text-white rounded-full font-bold text-lg shadow-xl hover:bg-slate-800 transition-all transform hover:-translate-y-1 overflow-hidden"
            >
                <span className="relative z-10">Get Started</span>
                <ArrowRight className="w-5 h-5 relative z-10 group-hover:translate-x-1 transition-transform" />
            </button>
            <p className="text-xs text-slate-400 max-w-xs text-center">
              A paid API key selection from <a href="https://ai.google.dev/gemini-api/docs/billing" target="_blank" className="underline">Google Cloud</a> is required for high-fidelity features.
            </p>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 w-full max-w-5xl">
        <div className="glass-card p-6 rounded-2xl border-t-4 border-t-emerald-500">
            <BrainCircuit className="w-6 h-6 text-emerald-600 mb-4" />
            <h3 className="font-bold text-lg text-slate-800 mb-2">Deep Reasoning</h3>
            <p className="text-sm text-slate-600">Context-aware strategies generated by Gemini 3 Pro.</p>
        </div>
        <div className="glass-card p-6 rounded-2xl border-t-4 border-t-indigo-500">
            <Gamepad2 className="w-6 h-6 text-indigo-600 mb-4" />
            <h3 className="font-bold text-lg text-slate-800 mb-2">Simulation</h3>
            <p className="text-sm text-slate-600">Visual roleplay scenarios powered by Gemini 2.5 Flash Image.</p>
        </div>
        <div className="glass-card p-6 rounded-2xl border-t-4 border-t-rose-500">
            <Mic className="w-6 h-6 text-rose-600 mb-4" />
            <h3 className="font-bold text-lg text-slate-800 mb-2">Live Voice</h3>
            <p className="text-sm text-slate-600">Real-time conversational guidance via Gemini Live API.</p>
        </div>
      </div>
    </div>
  );
};

export default WelcomeScreen;
